language: node_js
sudo: false
node_js:
  - "node"
  - "iojs"
  - "0.12"
  - "4"
  - "5"
  - "6"
services:
  - mysql
  - redis-server
after_script:
  - npm run coverage
before_install
  - mysql -e 'create database hbjs';