language: node_js
sudo: required
dist: trusty
node_js:
  - "node"
  - "iojs"
  - "0.12"
  - "4"
  - "5"
  - "6"
services:
  - mysql
  - redis-server
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
after_script:
  - npm run coverage
before_install:
  - mysql -u root -e 'CREATE DATABASE hbjs';
  - mysql -u root -e "CREATE USER 'hbjs'@'localhost' IDENTIFIED BY 'HBjs123456';"
  - mysql -u root -e "GRANT ALL ON hbjs.* TO 'makler'@'localhost';"